#!/usr/bin/tcsh -f

(cd doc && ./create-dok)

make mydist

rpmbuild -tb --target i386 vilistextum-*.tar.gz

set verbose
#set echo

set DEST=/home/bubi/homepage/xweb-1.0RC2/homepage/content/vilistextum 

cp doc/*.xhtml $DEST
cp doc/*.xml $DEST
cp old/vilistextum* $DEST
cp CHANGES $DEST

