#!/usr/bin/tcsh -f

(cd doc && ./create-dok)

make mydist

# rpmbuild -tb --target i386 vilistextum-*.tar.gz
# cp /usr/src/packages/SRPMS/vilistextum-*.src.rpm .
# cp /usr/src/packages/RPMS/i386/vilistextum-*.rpm .


set verbose
#set echo

set DEST=/home/bubi/homepage/xweb-1.0RC2/homepage/content/vilistextum 

cp doc/*.xhtml $DEST
cp doc/*.xml $DEST
cp old/vilistextum* $DEST
cp CHANGES $DEST

