# compile options
# change what you need 

CC = m68k-amigaos-gcc 
CFLAGS = -Wall -I. -O2

all: vilistextum copy

vilistextum: getopt_l.o latin1.o microsoft.o fileio.o html_tag.o main.o util.o html.o lists.o text.o
	$(CC) -o vilistextum.amiga getopt_l.o latin1.o microsoft.o fileio.o html_tag.o main.o util.o html.o lists.o text.o

copy:
	cp vilistextum.amiga /home/amiga/exchange/vilistextum
	chmod 777 /home/amiga/exchange/vilistextum

clean: 
	rm -f *.o vilistextum.amiga
